Update master_doot.yml

diff --git a/.github/workflows/master_doot.yml b/.github/workflows/master_doot.yml
--- a/.github/workflows/master_doot.yml
+++ b/.github/workflows/master_doot.yml
@@ -23,18 +23,20 @@ jobs:
           cd glambot
           npm install
           npm run build
-          zip -r release.zip dist/
-          
+          # Verify if dist/ exists and contains files
+          if [ -d "dist" ] && [ "$(ls -A dist)" ]; then
+            zip -r release.zip dist/
+          else
+            echo "Error: dist/ folder is empty or not found"
+            exit 1
+          fi
+
       - name: Upload artifact for deployment
         uses: actions/upload-artifact@v3
         with:
           name: node-app
           path: release.zip
 
-      - name: Zip artifact for deployment
-        run: zip -r release.zip dist/*
-
-      
   deploy:
     runs-on: ubuntu-latest
     needs: build
